#!/bin/bash

find ALL -maxdepth 1 -mindepth 1 -type d -exec sh -c '(echo -n {} && cd {} && git status -s && echo)' \;
find ALL -maxdepth 1 -mindepth 1 -type d -exec ls {}/.git>/dev/null  \;

echo CONSIDER:
echo 'ls -1  ALL/*/.git/config | xargs -n 1 grep jarogames'
echo 'cat  ALL/*/.tags | sort | uniq '
